version: "3"
services:
  registryservice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    command: pnpm start
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: patient-user
      POSTGRES_DB: patient-db
